steps:
  - command: "something.bat"
    label: "Push"
    if: |
      // Don't trigger builds from commits made by the build system
      // Note: This only skips step, we also skip the build completely with [skip ci].
      build.author.name !~ /buildsystem/ && build.branch =~ /development/
    agents:
      queue: "deploy"
    message: "${BUILDKITE}"
