steps:
  - group: "Group 1"
    steps:
    - command: echo "Group 1, step 1"
    - command: echo "Group 1, step 2"

  - group: "Group 2"
    steps:
    - command: echo "Group 2, step 1"
    - command: echo "Group 2, step 2"

  - group: ~
    steps:
    - command: echo "No group name, step 1"
    - command: echo "No group name, step 2"
