steps:
  - group: "Group 1"
    steps:
    - command: echo "Group 1, step 1"

  - group: "Group 2"
    steps:
    - command: echo "Group 2, step 1"

  - command: |
      echo "\`\`\`term
      x1b[31mFailure/Error:x1b[0m x1b[32mexpect\x1b[0m(new_item.created_at).to eql(now)

      x1b[31m  expected: 2018-06-20 19:42:26.290538462 +0000x1b[0m
      x1b[31m       got: 2018-06-20 19:42:26.290538000 +0000x1b[0m

      x1b[31m  (compared using eql?)x1b[0m\`\`\`" | buildkite-agent annotate 
